language: node_js
sudo: false
matrix:
  include:
    # linux builds
    - os: linux
      node_js:
        - "8"
        - "10"
        - "12"
      env: 
        - CXX="g++-4.9"
        - CC=gcc-4.9
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - gcc-4.9
          - g++-4.9
    - os: osx
      node_js:
        - "8"
        - "10"
        - "12"
      osx_image: xcode11
      compiler: clang
      env: 
        - CXX=g++
        - CC=gcc
before_script:
- npm run install-debug
before_deploy:
- npm install
- npm run prebuild
- npm run prebuild-electron
deploy:
  provider: releases
  api_key:
    secure: DU537mo7UzDlB0tgd/CX6VDwi2tE1KuBfEEO5+YBD9EfPNPbgs8NPOxdpBOhJIuuclHqouHF9JQ+L4plaQvRqNOoS2BT7fuftKfgzDamBchHgW9xi3TkF03YG5EFDgnb8NeAW2Ke5sABAS8dep3JL/AAeiQQ/SWDZAlhosW3OmGCDT8pCeV5nLQ/wwf0WMkkeEXCvJ6iA16SLf7FknNPdWU213noB2bHgLaku7Ozxt6256ntuBARABDZj6zgLPTCl7AOu+CjhIRCg/ogdyY6C8qWkBAQt97Rdz7wSbE7ub/AdOcdR2SynG6NeuPIxojT9Iy3jpYuULF9dJo+NwsPvBtTES7FS4LtNDglunQG98VT1A1rc+LbYBLxWELe9usQO3i1dDvf/KOUMOt5vLBpiffZq34rMnNsAlZepmyYLsp9Ui212jHZhcGPk8vFqX0BCyJUN6wzyp6KRGCRYInbKMJJoJyrYUk2AWoaxojdQf/Ha1Kb2xJfCep+Ny6nI9oyGFh8P937/6wjtLa8Drgrt15o5kkaUR5HluEBINgrYj/3VNgZkZWX1YG2eW3HiOylU/aBtrpKM7n4FYJfAiqAJbZ7FkK+Lk65sdLit0wrvt+8EO+GG8RUreXSf21iJmvjX/A106cGCpiC4AKG1drJjjxbCi/iTRid/+Aldq98k5A=
  file: prebuilds/*
  file_glob: true
  skip_cleanup: true
  on:
    repo: danielbarela/better-sqlite3
    tags: true
    node_js: "10"